Desktop/College/Computer Science/4th Year/SAD 2 - Original Version/jcsd-project-master (1)/jcsd-project-master/bookingsystem/urls.py
from django.urls import include, path
from django.contrib import admin
from django.urls import path
from bookingsystem import views

urlpatterns = [
    path('', views.Home, name="home"),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("account/", include("users.urls")),
    path("employee/", include("employee.urls")),
    path("inventory/", include("inventory.urls")),
    path("external/", include("external.urls")),
    path("profile", views.ViewProfile, name="profile"),
    path("update-profile", views.UpdateProfile, name="update-profile"),
    path("book", views.StartBooking, name="book"),
    path("register-booking", views.RegisterBooking, name="register-booking"),
    path("my-bookings", views.UserBookingsList, name="user-bookings"),
    path("my-bookings/<bookingId>", views.BookingDetails, name="booking-details"),
    path("print-booking/<bookingId>", views.PrintBooking, name="print-booking"),
]

Desktop/College/Computer Science/4th Year/SAD 2 - Original Version/jcsd-project-master (1)/jcsd-project-master/users/urls.py
from django.urls import include, path
from django.contrib import admin
from django.urls import path

from users import views

urlpatterns = [
    path('login', views.LogIn, name="login"),
    path('signup', views.SignUp, name="signup"),
    path(
        'logout/', views.LogoutAccount, name="logout"
    ),
    path(
        'create/', views.CreateAccount, name="create-account"
    ),
    
]

Desktop/College/Computer Science/4th Year/SAD 2 - Original Version/jcsd-project-master (1)/jcsd-project-master/users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _
from services.models import *

class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
    """User model."""
    email = models.EmailField(unique=False)
    accessLevel = models.CharField(max_length=255, default="user")
    objects = UserManager()

class Profile(models.Model):
    class ProfileTypes(models.TextChoices):
            STEM = "EMP", _("employee")
            ABM = "USER", _("user")

    class EmployeePositions(models.TextChoices):
            TECHNICIAN = "TECH", _("Technician")
            JRTECHNICIAN = "JRTECH", _("Jr. Technician")
            SMM = "SMM", _("Social Media Manager")
            MM = "MM", _("Marketing Manager")

    userId = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=True)
    firstName = models.CharField(max_length=255, null=True, blank=True)
    middleName = models.CharField(max_length=255, null=True, blank=True)
    lastName = models.CharField(max_length=255, null=True, blank=True)
    birthdate = models.CharField(max_length=255, null=True, blank=True)
    mobileNum = models.CharField(max_length=255, null=True, blank=True)
    profileType = models.CharField(max_length=100, choices=ProfileTypes.choices, default="USER")
    #FOR EMPLOYEE PROFILE
    emailAddress = models.CharField(max_length=255, null=True, blank=True)
    position = models.CharField(max_length=255, choices=EmployeePositions.choices, null=True, blank=True)
    employmentStatus = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.profileType} | {self.id} - {self.firstName} {self.middleName} {self.lastName}"

class Address(models.Model):
    profileId = models.ForeignKey(Profile, on_delete=models.CASCADE)
    streetAddress= models.CharField(max_length=255, null=True, blank=True)
    city= models.CharField(max_length=255, null=True, blank=True)
    province= models.CharField(max_length=255, null=True, blank=True)
    country= models.CharField(max_length=255, null=True, blank=True)
    zipcode= models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f"{self.profileId.lastName}'s Address"
    
class UserBookings(models.Model):
    userId = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, db_constraint=False)
    serviceId = models.ForeignKey(ServicesOffered, on_delete=models.CASCADE)
    locationId = models.ForeignKey(ServiceLocation, on_delete=models.CASCADE)
    date = models.CharField(max_length=255)
    time = models.CharField(max_length=255)
    status = models.CharField(max_length=255, default="Pending confirmation")
    assignedEmployee = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    #serviceFee
    #additionalFee
    #totalPrice
    #additional purchases
    #additional services

    def __str__(self):
        return f"{self.userId.username} - {self.date} || {self.time}" 

'''
class EmployeeAccount(models.Model):
    employeeId
    accessLevel
    CompanyRole
    EmployeeType
    isCommissionBased
'''

Desktop/College/Computer Science/4th Year/SAD 2 - Original Version/jcsd-project-master (1)/jcsd-project-master/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>JCSD Booking System</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% tailwind_css %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/icon.svg' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
{% include "partials/navbar.html" %}
<div class="w-full h-[1139px] home-bg bg-cover z-0">
    <div class="absolute bg-black opacity-50 z-10 w-full h-[1139px] ">
    </div>
    {% block content %}
    {% endblock %}
</div>

<!-- MESSAGE MODAL -->
{% if messages %}
<div id="message-modal" class=" h-full pt-[18%] xl:pt-[10%] w-full fixed z-30 overflow-auto left-[0] top-[0] bg-[rgb(0,0,0)] bg-[rgba(0,0,0,0.4)]">
    <div class="w-[280px] xl:w-[400px] p-5 m-auto bg-white rounded-[10px]">
        <div id="withdraw-confirmation" class=""> <!--MODAL FOR WITHDRAWAL CONFIRMATION -->
            <div class="flex flex-row">
                <button onclick="RemoveMessageModal()" class="count-2 ml-auto mt-2 mr-2"><b>&#10005;</b></button>
            </div>
            <div class="w-[100%] m-auto text-center p-5 xl:p-10">
                {% for message in messages %}
                <p class="font-[500] text-[18px] xl:text-[20px] 2xl:text-[24px] Montserrat">{{ message }}</p>
                {% endfor %}
            </div>
            <div class="flex flex-row text-[16px] justify-center">
                <button onclick="RemoveMessageModal()" class="ml-2 border-0 bg-[#00AEEF] px-[3rem] py-[.40rem] font-[500] text-white Montserrat">Ok</button>
            </div><br>
        </div>
    </div>
</div>
{% endif %}

{% block extra_js %}
{% endblock %}
<script>
    function OpenModal(){
        document.getElementById('logout-modal').classList.remove('hidden')
    }
    function RemoveModal(){
        document.getElementById('logout-modal').classList.add('hidden')
    }
    function RemoveMessageModal(){
        document.getElementById('message-modal').classList.add('hidden')
    }
</script>
</html>

Desktop/College/Computer Science/4th Year/SAD 2 - Original Version/jcsd-project-master (1)/jcsd-project-master/templates/bookingdetails.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="flex w-[90%] m-auto">
    <div class="mt-16 w-[1125px] h-[1030px] z-20 bg-white m-auto rounded-[10px]">
        <div class="flex flex-col w-[90%] h-full m-auto Montserrat mt-10" id="booking-details"> 
            <span class="text-[26px] font-bold">Booking Details</span>
            <div class="grid-cols-2 grid">
                <div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Booking ID</b></span>
                        <span>{{ bookingDetails.id }}</span>
                    </div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Customer</b></span>
                        <span>{{ profileData.profileId.firstName }} {{ profileData.profileId.MiddleName }} {{ profileData.profileId.lastName }}</span>
                    </div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Date and Time</b></span>
                        <span id="booking-date">{{ bookingDetails.date }} | {{ bookingDetails.time }}</span>
                    </div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Service</b></span>
                        <span>{{ bookingDetails.serviceId.serviceName }}</span>
                    </div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Location</b></span>
                        <span>{{ bookingDetails.locationId.location }}</span>
                    </div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Address</b></span>
                        <span>{{ profileData.streetAddress }}</span>
                    </div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Contact Number</b></span>
                        <span>{{ profileData.profileId.mobileNum }}</span>
                    </div>
                </div>
                <div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Assigned Employee</b></span>
                        <span></span>
                    </div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Base Price</b></span>
                        <span>Php. {{ bookingDetails.serviceId.priceRange }}</span>
                    </div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Service Fee</b></span>
                        <span></span>
                    </div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Additional Fees</b></span>
                        <span></span>
                    </div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Total</b></span>
                        <span></span>
                    </div>
                    <div class="mt-8 text-[20px] ml-8 flex flex-col">
                        <span><b>Booking Status</b></span>
                        <span>{{ bookingDetails.status }}</span>
                    </div>
                </div>
            </div>
            <div class="m-auto flex flex-row gap-[10px] text-white">
                <a href="{% url 'user-bookings' %}"
                class="cursor-pointer ml-2 rounded-[10px] p-5 w-[120px] h-[50px] bg-[#00AEEF] mt-5 auto-align-middle-row gap-[15px] text-[17px] hover:gap-[25px] transition-auto"><i class="fa-solid fa-angle-left"></i>
                Back</a>
                {% if bookingDetails.status == "Paid" %}
                <button
                onclick="generateReceipt()"
                class="cursor-pointer ml-2 rounded-[10px] p-5 w-[120px] h-[50px] bg-[#00AEEF] mt-5 auto-align-middle-row text-[17px] hover:text-[18px] transition-auto">
                Receipt</button>
                {% endif %}
            </div>
        </div>
        <div class="flex-col w-[90%] h-full m-auto Montserrat mt-10 hidden" id="booking-receipt">
            <span class="text-[20px] font-bold">Receipt</span>
            <div class="text-[18px] ml-6">
                <div class="mt-6 flex flex-row gap-[10px]">
                    <span>Booking ID:</span>
                    <span>{{ bookingDetails.id }}</span>
                </div>
                <div class="mt-6  flex flex-row gap-[10px]">
                    <span>Purok 4 Block 3 <br/>
                        Panacan Relocation <br/>
                        8000 Davao City, Philippines <br/>
                        0976 074 7797 <br/>
                        JCSD
                    </span>
                </div>
                
                <table class="w-[95%] booking-table mt-4">
                    <thead>
                        <th class="text-left w-[64%]">Description</th>
                        <th class="text-center w-[18%]">Quantity</th>
                        <th class="text-center w-[18%]">Amount</th>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><b>Subtotal</b></td>
                            <td>9</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><b>Additional Fee</b></td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><b>Total</b></td>
                            <td>12</td>
                        </tr>
                    </tbody>
                </table>
                <a 
                class="text-white cursor-pointer ml-auto mr-[46px] rounded-[10px] p-5 w-[120px] h-[50px] bg-[#00AEEF] mt-5 auto-align-middle-row text-[17px] hover:text-[18px] transition-auto"
                href="{% url 'print-booking' bookingDetails.id %}" target="_blank">Print</a>
            </div>
            
        </div>
    </div>
</div>
<script>
    function convertStringToDate(inputString) { //STRING TO DATE FUNCTION
        var parts = inputString.split(' | ');
        var dateParts = parts[0].split('-');
        var timeParts = parts[1].split(':');
        var months = ['Jan.', 'Feb.', 'Mar.', 'Apr.', 'May', 'Jun.', 'Jul.', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.'];
        var month = months[parseInt(dateParts[0], 10) - 1];
        var day = parseInt(dateParts[1], 10);
        var year = parseInt(dateParts[2], 10);
        var hour = parseInt(timeParts[0], 10);
        var minute = parseInt(timeParts[1], 10);
        var period = hour >= 12 ? 'pm' : 'am';
        if (hour > 12) {
            hour = hour - 12;
        }
        return `${month} ${day}, ${year}, ${hour}:${minute.toString().padStart(2, '0')} ${period}`;
    }
    var bookingDate = document.getElementById("booking-date")
    bookingDate.innerHTML = convertStringToDate(bookingDate.innerHTML)
</script>
<script>
    function generateReceipt(){
        bookDetailsDiv = document.getElementById("booking-details")
        receiptDiv = document.getElementById("booking-receipt")
        bookDetailsDiv.classList.add("hidden")
        receiptDiv.classList.add("flex")
        receiptDiv.classList.remove("hidden")
    }
</script>
{% endblock %}

Desktop/College/Computer Science/4th Year/SAD 2 - Original Version/jcsd-project-master (1)/jcsd-project-master/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if not user.is_staff %}
<div class="grid grid-cols-2 w-[90%] m-auto">
    <div class="flex flex-col text-white z-20 mt-32 w-[90%]">
        <img src="{% static 'images/logo.svg' %}" alt="jcsd logo"/>
        <div class="flex flex-col ml-2 Montserrat">
            <span class="text-[67px]">MAINTENANCE</span>
            <span class="text-[20px]">Our company provides quality services to people 
                at homes with computers. We have the equipment to 
                deep clean and restore any computer components to 
                its former glory!
            </span>
        </div>
        
        <a href="{% if user.is_authenticated %} {% url 'book' %} {% else %} {% url 'login' %} {% endif %}">
            <div class="cursor-pointer ml-2 rounded-[10px] w-[320px] h-[100px] bg-[#00AEEF] mt-5 auto-align-middle-row gap-[15px]  hover:gap-[25px] transition-auto">
                <span class="mt-[-2px] Montserrat text-[40px]">Book Now</span>
                <img src="{% static 'images/arrow-right.svg' %}" alt="arrow right"/>
            </div>
        </a>
    </div>
</div>
{% endif %}
{% endblock %}

Desktop/College/Computer Science/4th Year/SAD 2 - Original Version/jcsd-project-master (1)/jcsd-project-master/templates/printbase.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>JCSD Booking System</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% tailwind_css %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/icon.svg' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>

{% block content %}
{% endblock %}
</html>

Desktop/College/Computer Science/4th Year/SAD 2 - Original Version/jcsd-project-master (1)/jcsd-project-master/templates/printbooking.html
{% extends "printbase.html" %}
{% load static %}
{% block content %}
<div class="flex w-[100%] m-auto">
    <div class="mt-16 w-[1125px] h-[1030px] z-20 bg-white m-auto rounded-[10px]">
        <div class="flex-col w-[100%] h-full m-auto Montserrat mt-10" id="booking-receipt">
            <span class="text-[18px] font-bold">Receipt</span>
            <div class="text-[14px] ml-6">
                <div class="mt-6 flex flex-row gap-[10px]">
                    <span>Booking ID:</span>
                    <span>{{ bookingDetails.id }}</span>
                </div>
                <div class="mt-2 flex flex-row gap-[10px]">
                    <span>Date:</span>
                    <span id="booking-date">{{ bookingDetails.date }} | {{ bookingDetails.time }}</span>
                </div>
                <div class="mt-6  flex flex-row gap-[10px]">
                    <span>Purok 4 Block 3 <br/>
                        Panacan Relocation <br/>
                        8000 Davao City, Philippines <br/>
                        0976 074 7797 <br/>
                        JCSD
                    </span>
                </div>
                
                <table class="w-[95%] booking-table mt-4">
                    <thead>
                        <th class="text-left w-[60%]">Description</th>
                        <th class="text-center w-[20%]">Quantity</th>
                        <th class="text-center w-[20%]">Amount</th>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><b>Subtotal</b></td>
                            <td>9</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><b>Additional Fee</b></td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><b>Total</b></td>
                            <td>12</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
        </div>
    </div>
</div>
<script>
    window.print()
    function convertStringToDate(inputString) { //STRING TO DATE FUNCTION
        var parts = inputString.split(' | ');
        var dateParts = parts[0].split('-');
        var timeParts = parts[1].split(':');
        var months = ['Jan.', 'Feb.', 'Mar.', 'Apr.', 'May', 'Jun.', 'Jul.', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.'];
        var month = months[parseInt(dateParts[0], 10) - 1];
        var day = parseInt(dateParts[1], 10);
        var year = parseInt(dateParts[2], 10);
        var hour = parseInt(timeParts[0], 10);
        var minute = parseInt(timeParts[1], 10);
        var period = hour >= 12 ? 'pm' : 'am';
        if (hour > 12) {
            hour = hour - 12;
        }
        return `${month} ${day}, ${year}, ${hour}:${minute.toString().padStart(2, '0')} ${period}`;
    }
    var bookingDate = document.getElementById("booking-date")
    bookingDate.innerHTML = convertStringToDate(bookingDate.innerHTML)
</script>

{% endblock %}

Desktop/College/Computer Science/4th Year/SAD 2 - Original Version/jcsd-project-master (1)/jcsd-project-master/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="flex w-full h-full">
    <div class="w-full h-full mt-36 bg-white z-20">
        <div class="flex flex-row w-[85%] m-auto "> 
            <div class="w-[335px] ">
                <div class="h-[190px] w-[190px] bg-white rounded-[50%] mt-[-90px]">
                    <img src="{% static 'images/avatar.svg' %}" alt="default pfp"/>
                </div>
                <div class="flex flex-col Montserrat text-[24px] gap-[10px] mt-6">
                    <span class="transition-auto hover:text-[26px] font-bold">Profile</span>
                    {% if user.is_staff %}
                    <a href="{% url 'emp-attendance' %}"><span class="transition-auto hover:text-[26px]">Attendance</span></a>
                    <a href="{% url 'emp-payslip' %}"><span class="transition-auto hover:text-[26px]">Payslip</span></a>
                    {% else %}
                    <a href="{% url 'user-bookings' %}"><span class="transition-auto hover:text-[26px]">Bookings</span></a>
                    {% endif %}
                    <a href="{% url 'logout' %}" class="transition-auto hover:text-[26px]">Logout</a>
                </div>
            </div>
            <div class="w-full mt-8 Montserrat">
                <span class="text-[36px] ">{{ profileData.profileId.firstName }} {{ profileData.profileId.MiddleName }} {{ profileData.profileId.lastName }}</span>
                <hr class="mt-3"/>
                <form id="sign-up-form" class="login-form mt-8" method="POST" onsubmit="return validateData();" action="{% url 'update-profile' %}"> {% csrf_token %}
                    <div class="grid grid-cols-2 gap-[30px] ">
                        <div class="flex flex-col gap-[10px]">
                            <span>First Name</span>
                            <input type="text" name="firstName" value="{{ profileData.profileId.firstName }}" required/>
                            <span>Middle Name</span>
                            <input type="text" name="middleName" value="{{ profileData.profileId.middleName }}" required/>
                            <span>Last Name</span>
                            <input type="text" name="lastName" value="{{ profileData.profileId.lastName }}" required/>
                            <span>Birthday</span>
                            <input type="text" name="bday" id="user-bday" value="{{ profileData.profileId.birthdate }}" required/>

                            <div>
                                <span>Contact Number</span>
                                <span class="ml-1 text-[12px] mt-[-2px] text-red-500" id="phone-num-error"></span>
                            </div>
                            <input id="phone-num-field" type="text" name="contactNumber" value="{{ profileData.profileId.mobileNum }}" required/>

                            <div>
                                <span>Email</span>
                                <span class="ml-1 text-[12px] mt-[-2px] text-red-500" id="email-error"></span>
                            </div>
                            <input type="text" name="email" id="email-field" value="{{ profileData.profileId.userId.email }}" required/>
                        </div>
                        <div class="flex flex-col gap-[10px]">
                            {% if request.user.is_staff %}
                            <span>Position</span>
                            <input type="text" value="{{ profileData.profileId.get_position_display }}" readonly/>
                            {% endif %}
                            <span>Address</span>
                            <input type="text" name="address" value="{{ profileData.streetAddress }}" required/>
                            <div class="grid grid-cols-2 gap-[20px]  mt-[10px]">
                                <div>
                                    <span>City</span>
                                    <input type="text" name="city" value="{{ profileData.city }}" required/>
                                </div>
                                <div>
                                    <span>Provice</span>
                                    <input type="text" name="province" value="{{ profileData.province }}" required/>
                                </div>
                                <div>
                                    <span>Country</span>
                                    <input type="text" name="country" value="{{ profileData.country }}" required/>
                                </div>
                                <div>
                                    <span>Zip Code</span>
                                    <input type="text" name="zipCode" value="{{ profileData.zipcode }}" required/>
                                </div>
                            </div>
                            <div class="m-auto mt-8 flex flex-col text-center">
                                <button type="submit" class="m-auto reg-submit-btn transition-auto hover:text-[18px]">
                                    Save Changes
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    function validateData(){
        phone = checkPhoneNum()
        email = checkEmail()
        if (!email || !phone ){
            return false
        }
        return true
    }
    
    function checkEmail(){
        let user_email = document.getElementById('email-field').value
        const isValidEmail = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(user_email);
        if (!isValidEmail){
            document.getElementById('email-field').classList.add("border-red-500")
            document.getElementById('email-error').innerHTML = "Must enter a valid email address"
            return false
        }
        else{
            document.getElementById('email-field').classList.remove("border-red-500")
            document.getElementById('email-error').innerHTML = ""
            return true
        }
    }
    function checkPhoneNum(){
        let phoneNum = document.getElementById('phone-num-field').value
        const isValidPhone = /^(09|\+639)\d{9}$/.test(phoneNum);

        if (!isValidPhone){
            document.getElementById('phone-num-field').classList.add("border-red-500")
            document.getElementById('phone-num-error').innerHTML = "Must enter a valid Phone Number"
            return false
        }
        else{
            document.getElementById('phone-num-field').classList.remove("border-red-500")
            document.getElementById('phone-num-error').innerHTML = ""
            return true
        }
    }

</script>
<script>
    function convertStringToDate(inputString) { //STRING TO DATE FUNCTION
        var parts = inputString;
        var dateParts = parts.split('-');
        var months = ['Jan.', 'Feb.', 'Mar.', 'Apr.', 'May', 'Jun.', 'Jul.', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.'];
        var month = months[parseInt(dateParts[1], 10) - 1];
        var day = parseInt(dateParts[2], 10);
        var year = parseInt(dateParts[0], 10);
        return `${month} ${day}, ${year}`;
        //return parts
    }
    document.getElementById("user-bday").value = convertStringToDate(document.getElementById("user-bday").value)
    
</script>
{% endblock %}